app = "tuev-smartcal-web"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  API_UPSTREAM = "https://tuev-smartcal-api.fly.dev"
  NEXT_PUBLIC_API_URL = ""

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 100

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
