"""50 E2E scenario definitions for LLM-as-Judge test suite.

Each scenario defines a persona + building context that a User-LLM will
role-play, plus expected extraction results for the Judge-LLM to evaluate.
"""

from dataclasses import dataclass, field


@dataclass
class E2EScenario:
    id: str
    name: str
    category: str
    persona: str
    gebaeude: str
    wissen: str
    absicht: str
    max_turns: int
    expected: dict = field(default_factory=dict)
    tricky_aspect: str = ""


# ═══════════════════════════════════════════════════════════════
# A. Gebäudetyp Coverage (13) — one per nutzung enum value
# ═══════════════════════════════════════════════════════════════

SCENARIOS = [
    E2EScenario(
        id="S01", name="Bürogebäude Standard",
        category="gebaeudetyp",
        persona="Facility Manager eines Versicherungskonzerns, technisch kompetent, kennt die Gebäudedaten gut",
        gebaeude="Bürogebäude in München-Schwabing, 4.500 m², 5 Stockwerke, Baujahr 2008, TN-C-S Netz",
        wissen="Kennt m², PLZ 80801, hat vor 2 Jahren TÜV-Prüfung gehabt für 4.200€",
        absicht="DGUV V3 Wiederholungsprüfung, möchte auch VdS-Angebot",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 4000, "flaeche_max": 5000, "kat": 2},
        tricky_aspect="Straightforward case — baseline for comparison",
    ),
    E2EScenario(
        id="S02", name="Service Center / Call Center",
        category="gebaeudetyp",
        persona="Betriebsleiter eines Call Centers, wenig technisches Wissen, eher ungeduldig",
        gebaeude="Service Center in Nürnberg, 1.200 m², Großraumbüro mit Server-Raum, EG + 1. OG",
        wissen="Kennt m² ungefähr, PLZ 90402, kein Referenzpreis",
        absicht="Nur DGUV V3, möglichst schnell ein Angebot",
        max_turns=4,
        expected={"nutzung": "service_center", "flaeche_min": 1000, "flaeche_max": 1500, "kat": 2},
        tricky_aspect="service_center is valid enum but rarely used — will LLM map correctly?",
    ),
    E2EScenario(
        id="S03", name="Seniorentreff",
        category="gebaeudetyp",
        persona="Hausmeister einer kleinen Gemeinde, spricht einfaches Deutsch, unsicher bei Fachbegriffen",
        gebaeude="Gemeindehaus / Seniorentreff in Freiburg, 350 m², eingeschossig, einfache Ausstattung",
        wissen="Weiß die m² vom Grundriss, PLZ 79098, Anlage sehr ordentlich gepflegt",
        absicht="Nur DGUV V3, ist Vereinsmitglied",
        max_turns=4,
        expected={"nutzung": "seniorentreff", "flaeche_min": 300, "flaeche_max": 400, "kat": 1},
        tricky_aspect="Small building, low category — minimum price edge case",
    ),
    E2EScenario(
        id="S04", name="Hotel mit Zimmerzahl",
        category="gebaeudetyp",
        persona="Hoteldirektorin, geschäftstüchtig, gibt Zimmeranzahl statt m², möchte alles aus einer Hand",
        gebaeude="4-Sterne-Hotel in Hamburg Zentrum, 180 Zimmer, Restaurant, Wellnessbereich, Tiefgarage",
        wissen="Kennt nur Zimmerzahl und Sternekategorie, nicht die genaue m²-Zahl, PLZ 20095",
        absicht="DGUV V3 + VdS, fragt auch nach Blitzschutz",
        max_turns=4,
        expected={"nutzung": "hotel", "flaeche_min": 4500, "flaeche_max": 6500, "kat": 2},
        tricky_aspect="Gives rooms not m² — coordinator must convert 180×30=5400m²",
    ),
    E2EScenario(
        id="S05", name="Krankenhaus",
        category="gebaeudetyp",
        persona="Technischer Leiter eines Kreiskrankenhauses, kennt die Technik, spricht Fachjargon",
        gebaeude="Krankenhaus in Würzburg, 15.000 m², 6 Stationen, OP-Bereich, Intensiv, NEA vorhanden",
        wissen="Kennt m², hat NEA + Sicherheitsstromversorgung, PLZ 97070, letzte Prüfung 2024 für 12.800€",
        absicht="DGUV V3, NEA und SV-NSHV sollen berücksichtigt werden",
        max_turns=4,
        expected={"nutzung": "krankenhaus", "flaeche_min": 14000, "flaeche_max": 16000, "kat": 2},
        tricky_aspect="Krankenhaus is Kat 2, NOT Kat 5 — common LLM mistake",
    ),
    E2EScenario(
        id="S06", name="Industriegebäude",
        category="gebaeudetyp",
        persona="Werksleiter eines Automotive-Zulieferers, kennt seine Anlage detailliert",
        gebaeude="Produktionshalle in Regensburg, 8.000 m², Maschinenpark, 3 NSHV, Trafostation",
        wissen="Kennt m², Anzahl NSHV, hat MS-Trafo, PLZ 93047",
        absicht="DGUV V3, keine VdS nötig",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 7000, "flaeche_max": 9000, "kat": 3},
        tricky_aspect="Industrie is Kat 3, mentions NSHV and Trafo which affect pricing",
    ),
    E2EScenario(
        id="S07", name="Schule",
        category="gebaeudetyp",
        persona="Schulleiter eines Gymnasiums, pädagogisch orientiert, wenig technisches Interesse",
        gebaeude="Gymnasium in Heidelberg, 5.500 m², Hauptgebäude + Turnhalle + Werkräume, Baujahr 1975",
        wissen="Kennt ungefähre m² vom Schulträger, PLZ 69115, erste Prüfung an dieser Schule",
        absicht="DGUV V3, Schulträger verlangt es",
        max_turns=4,
        expected={"nutzung": "schule", "flaeche_min": 5000, "flaeche_max": 6000, "kat": 2},
        tricky_aspect="Old building (1975) — reifegrad might be lower",
    ),
    E2EScenario(
        id="S08", name="Verkaufsstätte / Elektronikmarkt",
        category="gebaeudetyp",
        persona="Filialleiter eines Elektronikmarkts, praktisch orientiert",
        gebaeude="Elektronikmarkt in Augsburg, 3.000 m² Verkaufsfläche, Lager im UG 800 m²",
        wissen="Kennt Verkaufsfläche, schätzt Gesamtfläche auf 3.800m², PLZ 86150",
        absicht="Nur DGUV V3",
        max_turns=4,
        expected={"nutzung": "verkaufsstaette", "flaeche_min": 3500, "flaeche_max": 4200, "kat": 3},
        tricky_aspect="Gives Verkaufsfläche + Lager separately — must sum to total",
    ),
    E2EScenario(
        id="S09", name="Tiefgarage",
        category="gebaeudetyp",
        persona="Hausverwaltung einer Wohnanlage, gibt Stellplätze statt m²",
        gebaeude="Tiefgarage unter Wohnanlage in Stuttgart, 180 Stellplätze, 2 Ebenen",
        wissen="Kennt nur Stellplatzzahl, nicht m², PLZ 70173",
        absicht="Nur DGUV V3",
        max_turns=4,
        expected={"nutzung": "tiefgarage", "flaeche_min": 4000, "flaeche_max": 5000, "kat": 1},
        tricky_aspect="Gives Stellplätze not m² — coordinator must convert 180×25=4500m²",
    ),
    E2EScenario(
        id="S10", name="Versammlungsstätte",
        category="gebaeudetyp",
        persona="Veranstaltungsmanager einer Stadthalle, kennt den Betrieb gut",
        gebaeude="Stadthalle in Leipzig, 2.800 m², Großer Saal 1.200 Plätze, Foyer, Backstage, Technik",
        wissen="Kennt m², PLZ 04109, Anlage in gutem Zustand (Reifegrad 3)",
        absicht="DGUV V3, kein Vereinsmitglied",
        max_turns=4,
        expected={"nutzung": "versammlungsstaette", "flaeche_min": 2500, "flaeche_max": 3200, "kat": 3},
        tricky_aspect="Not a member — 20% surcharge should apply",
    ),
    E2EScenario(
        id="S11", name="Möbelhaus",
        category="gebaeudetyp",
        persona="Geschäftsführer eines Einrichtungshauses, kaufmännisch orientiert",
        gebaeude="Einrichtungshaus in Karlsruhe, 12.000 m², große Ausstellungsfläche, Restaurant",
        wissen="Kennt m², PLZ 76131, hat Rahmenvertrag",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "moebelhaus", "flaeche_min": 11000, "flaeche_max": 13000, "kat": 3},
        tricky_aspect="Large Verkaufsstätte variant — moebelhaus enum",
    ),
    E2EScenario(
        id="S12", name="Gartenmarkt",
        category="gebaeudetyp",
        persona="Betriebsleiter eines Gartencenters, gibt Innen + Außenfläche separat an",
        gebaeude="Gartencenter in Ulm, 9.000 m² Halle + 4.000 m² überdachte Außenfläche",
        wissen="Kennt beide Flächen, PLZ 89073, fragt ob Außenfläche zählt",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "gartenmarkt", "flaeche_min": 9000, "flaeche_max": 14000, "kat": 3},
        tricky_aspect="Innen vs Außenfläche — should system ask or include both?",
    ),
    E2EScenario(
        id="S13", name="Sonstige — Kirche",
        category="gebaeudetyp",
        persona="Kirchengemeinderat, spricht formell, unsicher welche Kategorie passt",
        gebaeude="Historische Kirche in Bamberg, 800 m², Kirchenschiff + Gemeindesaal + Sakristei",
        wissen="Kennt m² vom Bauamt, PLZ 96047, Gebäude unter Denkmalschutz",
        absicht="DGUV V3, fragt ob Denkmalschutz relevant ist",
        max_turns=4,
        expected={"nutzung": "versammlungsstaette", "flaeche_min": 700, "flaeche_max": 900, "kat": 3},
        tricky_aspect="Kirche mit Gemeindesaal — versammlungsstaette is reasonable mapping",
    ),

    # ═══════════════════════════════════════════════════════════════
    # B. Tricky Extraction (10) — realistic input challenges
    # ═══════════════════════════════════════════════════════════════

    E2EScenario(
        id="S14", name="L×B×Etagen statt m²",
        category="tricky",
        persona="Betriebsleiter einer Lagerhalle, kennt keine m², beschreibt die Halle in Abmessungen",
        gebaeude="Lagerhalle in Hannover, ca. 45×20 Meter, auf 2 Etagen, einfache Ausstattung",
        wissen="Kennt nur Abmessungen, nicht m², PLZ 30159",
        absicht="Nur DGUV V3",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 1500, "flaeche_max": 2000, "kat": 2},
        tricky_aspect="Gives dimensions — coordinator must compute 45×20×2=1800m²",
    ),
    E2EScenario(
        id="S15", name="Pflegeheim — Branchenbegriff",
        category="tricky",
        persona="Einrichtungsleiterin eines Pflegeheims, spricht von 'Bewohnern' statt Fläche",
        gebaeude="Pflegeheim in Passau, 60 Bewohner, 3 Wohngruppen, Pflegebad, Gemeinschaftsräume",
        wissen="Kennt Bewohnerzahl und Zimmer, aber nicht m², PLZ 94032",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "krankenhaus", "flaeche_min": 2500, "flaeche_max": 4000, "kat": 2},
        tricky_aspect="'Pflegeheim' must map to krankenhaus or seniorentreff — ambiguous",
    ),
    E2EScenario(
        id="S16", name="Mischnutzung — Verwaltung + Kantine",
        category="tricky",
        persona="FM einer Stadtverwaltung, beschreibt die Nutzung pro Etage",
        gebaeude="Verwaltungsgebäude in Darmstadt, EG: Kantine+Archiv, 1-3 OG: Büros, UG: Technik, gesamt 6.500m²",
        wissen="Kennt m² und Nutzungsverteilung ungefähr: 70% Büro, 15% Kantine, 10% Archiv, 5% Technik",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 6000, "flaeche_max": 7000, "kat": 2},
        tricky_aspect="Mixed use — should extract nutzungs_mix with percentages",
    ),
    E2EScenario(
        id="S17", name="Hotel — m² unbekannt",
        category="tricky",
        persona="Hoteldirektorin eines Mittelklasse-Hotels, kennt Zimmerzahl aber keine Fläche",
        gebaeude="Mittelklasse-Hotel 3 Sterne in Kassel, 65 Zimmer, kein Restaurant, kein Wellness",
        wissen="Weiß nur: 65 Zimmer, 3 Etagen, PLZ 34117. Kennt m² nicht.",
        absicht="DGUV V3, fragt was das kostet",
        max_turns=4,
        expected={"nutzung": "hotel", "flaeche_min": 1500, "flaeche_max": 2500, "kat": 2},
        tricky_aspect="No m², no dimensions — coordinator must estimate from room count (65×30≈1950m²)",
    ),
    E2EScenario(
        id="S18", name="Kindertagesstätte / Kita",
        category="tricky",
        persona="Kita-Leiterin, spricht von 'Gruppen' und 'Kindern', wenig technisches Verständnis",
        gebaeude="Städtische Kita in Ulm, 8 Gruppen à 25 Kinder, Turnraum, Küche, Büro",
        wissen="Kennt Gruppenanzahl, Gebäude hat ca. 1.200m², PLZ 89073",
        absicht="DGUV V3, Stadt verlangt es",
        max_turns=4,
        expected={"nutzung": "schule", "flaeche_min": 1000, "flaeche_max": 1400, "kat": 2},
        tricky_aspect="'Kita' has no enum — should map to 'schule'",
    ),
    E2EScenario(
        id="S19", name="Baumarkt vs Gartenmarkt",
        category="tricky",
        persona="Marktleiter eines Baumarkts mit großer Gartenabteilung und Holzzuschnitt",
        gebaeude="Baumarkt in Ingolstadt, 7.500 m² Verkaufsfläche, 2.000 m² Gartenabteilung, Holzzuschnitt",
        wissen="Kennt Flächen getrennt, PLZ 85049",
        absicht="Nur DGUV V3",
        max_turns=4,
        expected={"nutzung": "gartenmarkt", "flaeche_min": 9000, "flaeche_max": 10000, "kat": 3},
        tricky_aspect="Baumarkt mit Garten → gartenmarkt or verkaufsstaette? Holzzuschnitt = Kat 3?",
    ),
    E2EScenario(
        id="S20", name="Vager Einstieg — nur 'Gewerbeimmobilie'",
        category="tricky",
        persona="Sekretariat einer Hausverwaltung, wenig Details, schickt kurze Anfrage",
        gebaeude="Unbekannt — Klient sagt nur 'Gewerbeimmobilie', keine Details",
        wissen="Weiß fast nichts, muss nachgefragt werden",
        absicht="'Brauche ein Angebot für eine Gewerbeimmobilie'",
        max_turns=4,
        expected={"nutzung": None, "flaeche_min": None, "flaeche_max": None},
        tricky_aspect="Too vague — coordinator MUST ask follow-up, NOT calculate immediately",
    ),
    E2EScenario(
        id="S21", name="Großbäckerei mit Laden",
        category="tricky",
        persona="Geschäftsführer einer Großbäckerei, beschreibt den Betrieb detailliert",
        gebaeude="Großbäckerei in Erlangen mit Ladengeschäft, Produktion 1.500m², Laden 200m², Büro 150m²",
        wissen="Kennt alle Flächen, PLZ 91052",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 1700, "flaeche_max": 2000, "kat": 3},
        tricky_aspect="'Bäckerei' with Produktion should map to industrie (not verkaufsstaette), possible nutzungs_mix",
    ),
    E2EScenario(
        id="S22", name="Adresskorrektur mid-conversation",
        category="tricky",
        persona="FM eines Bürogebäudes, macht Fehler bei der Adresse und korrigiert sich",
        gebaeude="Bürogebäude, 3.500 m², eigentlich in Mannheim (nicht München wie zuerst gesagt)",
        wissen="Kennt m², sagt zuerst München, korrigiert dann zu Mannheim PLZ 68159",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 3000, "flaeche_max": 4000, "kat": 2},
        tricky_aspect="Address correction in turn 2 — must recalculate with new PLZ/Reisekosten",
    ),
    E2EScenario(
        id="S23", name="Mehrere Gebäude auf Campus",
        category="tricky",
        persona="Facility Manager eines Unternehmens-Campus, fragt ob alles zusammen geht",
        gebaeude="3 Bürogebäude auf einem Campus in Garching, insgesamt 12.000 m²",
        wissen="Kennt Gesamtfläche, PLZ 85748, fragt ob man zusammen oder getrennt kalkuliert",
        absicht="DGUV V3 für den gesamten Campus",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 11000, "flaeche_max": 13000, "kat": 2},
        tricky_aspect="Multiple buildings — should coordinator advise one or split?",
    ),

    # ═══════════════════════════════════════════════════════════════
    # C. Multi-turn mit Recalculation (12) — neue Info ändert Preis
    # ═══════════════════════════════════════════════════════════════

    E2EScenario(
        id="S24", name="Reifegrad nachliefern",
        category="multiturn",
        persona="FM, startet mit Büro 3.000m², liefert danach Reifegrad 1 nach",
        gebaeude="Bürogebäude in Frankfurt, 3.000 m², ungeordnete Dokumentation",
        wissen="Kennt m², nach Rückfrage: Reifegrad 1, Unterlagen fehlen teilweise, PLZ 60311",
        absicht="DGUV V3",
        max_turns=5,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 2500, "flaeche_max": 3500, "kat": 2, "reifegrad": 1},
        tricky_aspect="Reifegrad 1 → +30% Zuschlag, must trigger recalculation",
    ),
    E2EScenario(
        id="S25", name="Referenzpreis nachliefern",
        category="multiturn",
        persona="Hoteldirektor, gibt nach erster Kalkulation den letzten Prüfpreis an",
        gebaeude="Hotel in Düsseldorf, 150 Zimmer, 4 Sterne",
        wissen="Kennt Zimmerzahl, sagt nach Rückfrage: letzte Prüfung 2023 für 5.800€, PLZ 40210",
        absicht="DGUV V3",
        max_turns=5,
        expected={"nutzung": "hotel", "flaeche_min": 4000, "flaeche_max": 5000, "kat": 2, "referenz": 5800},
        tricky_aspect="Referenzpreis comparison must appear in summary",
    ),
    E2EScenario(
        id="S26", name="PLZ nachliefern — weit weg",
        category="multiturn",
        persona="Werksleiter, gibt nach der ersten Kalkulation die PLZ in Sachsen an",
        gebaeude="Industriehalle in Wilsdruff bei Dresden, 6.000 m²",
        wissen="Kennt m², PLZ erst nach Rückfrage: 01723, PLZ ist weit von nächster NL",
        absicht="Nur DGUV V3",
        max_turns=5,
        expected={"nutzung": "industrie", "flaeche_min": 5500, "flaeche_max": 6500, "kat": 3},
        tricky_aspect="PLZ 01723 → hohe Reisekosten, must recalculate and show difference",
    ),
    E2EScenario(
        id="S27", name="Vollerfassung nachfordern",
        category="multiturn",
        persona="Schulverwaltungsbeamter, fordert nach erster Kalkulation Vollerfassung",
        gebaeude="Realschule in Heilbronn, 4.000 m²",
        wissen="Kennt m², PLZ 74072, Schulträger verlangt 100% Messdatenerfassung",
        absicht="DGUV V3 mit Vollerfassung",
        max_turns=5,
        expected={"nutzung": "schule", "flaeche_min": 3500, "flaeche_max": 4500, "kat": 2, "vollerfassung": True},
        tricky_aspect="Vollerfassung → +30% on Prüfkosten, must show in recalculation",
    ),
    E2EScenario(
        id="S28", name="Kein Vereinsmitglied",
        category="multiturn",
        persona="FM eines mittelständischen Betriebs, ist kein TÜV-Vereinsmitglied",
        gebaeude="Bürogebäude in Bielefeld, 2.500 m²",
        wissen="Kennt m², PLZ 33602, sagt nach Rückfrage: kein Rahmenvertrag, kein Vereinsmitglied",
        absicht="DGUV V3",
        max_turns=5,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 2000, "flaeche_max": 3000, "kat": 2, "vereinsmitglied": False},
        tricky_aspect="Non-member → +20% Zuschlag, must recalculate",
    ),
    E2EScenario(
        id="S29", name="VdS dazu bestellen",
        category="multiturn",
        persona="FM, bestellt nach erster DGUV-Kalkulation VdS 2871 dazu",
        gebaeude="Bürogebäude in Köln, 5.000 m², Versicherung verlangt VdS",
        wissen="Kennt m², PLZ 50667, Versicherung hat VdS-Prüfung verlangt",
        absicht="Erst nur DGUV V3, dann VdS dazu",
        max_turns=5,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 4500, "flaeche_max": 5500, "kat": 2, "vds": True},
        tricky_aspect="VdS as Zusatzleistung must appear in recalculated angebot",
    ),
    E2EScenario(
        id="S30", name="PV-Anlage nachliefern",
        category="multiturn",
        persona="Werksleiter, erwähnt nach erster Kalkulation die PV-Anlage auf dem Dach",
        gebaeude="Produktionshalle in Ingolstadt, 10.000 m², PV-Anlage 120 kWp auf dem Dach",
        wissen="Kennt m² und kWp, PLZ 85049, PV seit 2022",
        absicht="DGUV V3, PV soll mit geprüft werden",
        max_turns=5,
        expected={"nutzung": "industrie", "flaeche_min": 9000, "flaeche_max": 11000, "kat": 3, "pv_kwp": 120},
        tricky_aspect="PV as Zusatzleistung with DIN pricing",
    ),
    E2EScenario(
        id="S31", name="Ladesäulen nachliefern",
        category="multiturn",
        persona="Filialleiter Supermarkt, erwähnt die Wallboxen auf dem Parkplatz",
        gebaeude="Supermarkt in Aschaffenburg, 2.800 m², Parkplatz mit 8 Wallboxen à 2 Anschlüsse",
        wissen="Kennt m² und Wallbox-Details, PLZ 63739",
        absicht="DGUV V3, Wallboxen sollen mit geprüft werden",
        max_turns=5,
        expected={"nutzung": "verkaufsstaette", "flaeche_min": 2500, "flaeche_max": 3200, "kat": 3},
        tricky_aspect="Ladesäulen as Zusatzleistung, must appear in Angebot",
    ),
    E2EScenario(
        id="S32", name="NEA + Sicherheitsstromversorgung",
        category="multiturn",
        persona="Technischer Leiter Krankenhaus, nennt nach erster Kalkulation NEA und SV",
        gebaeude="Krankenhaus in Aachen, 18.000 m², NEA vorhanden, Sicherheitsstromversorgung, 8 OP-Säle",
        wissen="Kennt m² und technische Ausstattung, PLZ 52062",
        absicht="DGUV V3 mit Berücksichtigung NEA und SV-NSHV",
        max_turns=5,
        expected={"nutzung": "krankenhaus", "flaeche_min": 17000, "flaeche_max": 19000, "kat": 2},
        tricky_aspect="NEA + SV → additional pricing items, complex case",
    ),
    E2EScenario(
        id="S33", name="Erstprüfung statt Wiederholung",
        category="multiturn",
        persona="Projektleiter Neubau, Gebäude gerade fertiggestellt, Erstabnahme nötig",
        gebaeude="Neubau Bürogebäude in Darmstadt, 4.000 m², Fertigstellung Q2 2026",
        wissen="Kennt m², PLZ 64283, Erstprüfung = Neubau",
        absicht="DGUV V3 Erstprüfung (nicht Wiederholungsprüfung)",
        max_turns=5,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 3500, "flaeche_max": 4500, "kat": 2, "erstpruefung": True},
        tricky_aspect="Erstprüfung → +100% on Prüfkosten, biggest single modifier",
    ),
    E2EScenario(
        id="S34", name="Drei Zusatzleistungen auf einmal",
        category="multiturn",
        persona="Hoteldirektor, nennt in einem Satz PV + Ladesäulen + VdS",
        gebaeude="Hotel in Stuttgart, 200 Zimmer, PV 80 kWp, 4 Wallboxen, VdS gewünscht",
        wissen="Kennt Zimmer, PV-Leistung und Wallbox-Anzahl, PLZ 70173",
        absicht="DGUV V3 + VdS + PV + Ladesäulen in einem Durchgang",
        max_turns=5,
        expected={"nutzung": "hotel", "flaeche_min": 5000, "flaeche_max": 7000, "kat": 2, "vds": True, "pv_kwp": 80},
        tricky_aspect="Multiple Zusatzleistungen in one message — all must be captured",
    ),
    E2EScenario(
        id="S35", name="Nutzungsmix nachliefern",
        category="multiturn",
        persona="FM Industriekomplex, gibt nach erster Kalkulation den Nutzungsmix an",
        gebaeude="Industriekomplex in Wolfsburg, 20.000 m², gemischte Nutzung",
        wissen="Kennt m², gibt nach Rückfrage an: 40% Produktion, 30% Lager, 30% Verwaltung, PLZ 38440",
        absicht="DGUV V3 mit Nutzungsmix",
        max_turns=5,
        expected={"nutzung": "industrie", "flaeche_min": 18000, "flaeche_max": 22000, "kat": 3},
        tricky_aspect="Nutzungs-Mix after initial single-category calculation → weighted category",
    ),

    # ═══════════════════════════════════════════════════════════════
    # D. Realistische Edge Cases (8)
    # ═══════════════════════════════════════════════════════════════

    E2EScenario(
        id="S36", name="Sehr kleines Objekt — Vereinsheim",
        category="edge",
        persona="Vereinsvorsitzender eines Sportvereins, hat nur ein kleines Vereinsheim",
        gebaeude="Vereinsheim in Deggendorf, 120 m², einfachste Ausstattung, 1 Raum + Küche + WC",
        wissen="Kennt m², PLZ 94469, Gebäude sehr einfach",
        absicht="DGUV V3, muss wegen Versicherung",
        max_turns=4,
        expected={"nutzung": "sonstige", "flaeche_min": 100, "flaeche_max": 150, "kat": 1},
        tricky_aspect="Very small — Grundkosten dominate, low confidence expected",
    ),
    E2EScenario(
        id="S37", name="Sehr großes Objekt — Logistikzentrum",
        category="edge",
        persona="Logistikleiter eines großen Versandzentrums, kennt die Zahlen exakt",
        gebaeude="Logistikzentrum bei Nürnberg, 85.000 m², Hochregallager + Versand + Büro",
        wissen="Kennt m² exakt, PLZ 90431, 12 UV, 4 NSHV, 2 Trafos",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 80000, "flaeche_max": 90000, "kat": 2},
        tricky_aspect="Extreme size → many Prüftage, possibly multi-trip, high total",
    ),
    E2EScenario(
        id="S38", name="Klient nennt falsche Kategorie",
        category="edge",
        persona="FM, besteht darauf dass sein Büro Kategorie 5 sein soll",
        gebaeude="Bürogebäude in Erfurt, 2.000 m², normales Büro",
        wissen="Kennt m², PLZ 99084, behauptet 'wir haben Kategorie 5 wegen der Server'",
        absicht="DGUV V3, will Kat 5",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 1800, "flaeche_max": 2200, "kat": 2},
        tricky_aspect="Customer insists on wrong category — should coordinator correct or accept?",
    ),
    E2EScenario(
        id="S39", name="Nur Nutzung, keine Größe",
        category="edge",
        persona="Assistentin der GF, hat minimale Info, soll nur mal nachfragen",
        gebaeude="Bürogebäude in München, keine weiteren Details bekannt",
        wissen="Weiß nur: Bürogebäude, München. Kennt weder m² noch Zimmer noch Etagen.",
        absicht="'Wie viel kostet so eine Prüfung ungefähr?'",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": None, "flaeche_max": None},
        tricky_aspect="Missing required field m² — coordinator MUST ask, NOT guess",
    ),
    E2EScenario(
        id="S40", name="Gebäudetyp-Korrektur",
        category="edge",
        persona="Klient, der sich am Anfang vertut und Hotel sagt, aber Boardinghouse meint",
        gebaeude="Boardinghouse / Apartmenthaus in Berlin, 80 Apartments, kein Restaurant",
        wissen="Sagt erst 'Hotel', korrigiert dann: eigentlich Boardinghouse/Serviced Apartments, PLZ 10115",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "hotel", "flaeche_min": 2000, "flaeche_max": 3000, "kat": 2},
        tricky_aspect="Type correction mid-conversation — must not keep old params",
    ),
    E2EScenario(
        id="S41", name="Englischsprachiger Klient",
        category="edge",
        persona="Expat Facility Manager, speaks English, works at international firm in Munich",
        gebaeude="Office building in Munich, about 5.000 sqm, 4 floors, modern installation",
        wissen="Knows sqm, address, no previous TÜV inspection, PLZ 80333",
        absicht="DGUV V3 inspection, asking in English",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 4500, "flaeche_max": 5500, "kat": 2},
        tricky_aspect="English input — system prompt is German, should still extract correctly",
    ),
    E2EScenario(
        id="S42", name="Klient fragt nach Erklärung",
        category="edge",
        persona="Hausverwalterin, versteht die Kalkulation nicht, fragt nach Details",
        gebaeude="Wohn-/Geschäftshaus in Augsburg, 1.800 m², EG Gewerbe + OG Wohnungen",
        wissen="Kennt m², PLZ 86150, fragt: 'Was ist eine Installationskategorie? Wie kommt der Preis zustande?'",
        absicht="DGUV V3, möchte verstehen woraus der Preis besteht",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 1600, "flaeche_max": 2000, "kat": 2},
        tricky_aspect="Explanation request — coordinator should explain, not just calculate",
    ),
    E2EScenario(
        id="S43", name="Klient vergleicht mit Wettbewerb",
        category="edge",
        persona="GF eines Mittelständlers, hat Dekra-Angebot und will TÜV-Vergleich",
        gebaeude="Produktionsbetrieb in Schweinfurt, 4.500 m², hat Dekra-Angebot über 4.000€",
        wissen="Kennt m², PLZ 97421, hat Dekra-Angebot 4.000€, fragt ob TÜV günstiger ist",
        absicht="DGUV V3, will den Preis vergleichen",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 4000, "flaeche_max": 5000, "kat": 3},
        tricky_aspect="Competitor price mention — coordinator should NOT promise to beat it",
    ),

    # ═══════════════════════════════════════════════════════════════
    # E. Feature-Kombinationen (7) — alles zusammen
    # ═══════════════════════════════════════════════════════════════

    E2EScenario(
        id="S44", name="Maximum-Combo",
        category="combo",
        persona="FM eines Konzerngebäudes, gibt alle Infos auf einmal",
        gebaeude="Bürogebäude München, 8.000 m², PV 200 kWp, 10 DC-Ladesäulen, Referenz 2021 4.200€, Reifegrad 4",
        wissen="Kennt alles: m², PV, Ladesäulen, Referenzpreis, Reifegrad, PLZ 80331, VdS gewünscht",
        absicht="DGUV V3 + VdS + PV + Ladesäulen, alles zusammen",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 7500, "flaeche_max": 8500, "kat": 2, "vds": True, "pv_kwp": 200},
        tricky_aspect="Everything at once — all features must be captured in one pass",
    ),
    E2EScenario(
        id="S45", name="Teuerster Case — Krankenhaus max",
        category="combo",
        persona="Technischer Leiter Klinikum, kennt alle Details, braucht Maximal-Angebot",
        gebaeude="Großklinikum in Berlin, 25.000 m², NEA, SV-NSHV, 12 OP-Säle, Erstprüfung nach Sanierung",
        wissen="Kennt alles, PLZ 10117, Erstprüfung, Vollerfassung gewünscht, Eilzuschlag nötig, kein Mitglied",
        absicht="DGUV V3 Erstprüfung + Vollerfassung + Eilzuschlag",
        max_turns=4,
        expected={"nutzung": "krankenhaus", "flaeche_min": 24000, "flaeche_max": 26000, "kat": 2, "erstpruefung": True, "vollerfassung": True},
        tricky_aspect="All surcharges stacked — Erstprüfung +100%, Vollerfassung +30%, Eil +20%, Nicht-Mitglied +20%",
    ),
    E2EScenario(
        id="S46", name="Dreifach-Mix Industrie",
        category="combo",
        persona="Werkleiter eines großen Industriekomplexes, gibt Nutzungsmix sofort an",
        gebaeude="Industriekomplex in Wolfsburg, 50.000 m², 30% Büro / 40% Produktion / 30% Lager",
        wissen="Kennt m² und Mix, PLZ 38440, Reifegrad 3",
        absicht="DGUV V3 mit gewichtetem Kategoriemix",
        max_turns=4,
        expected={"nutzung": "industrie", "flaeche_min": 48000, "flaeche_max": 52000, "kat": 3},
        tricky_aspect="Large mixed-use industrial — nutzungs_mix must weight categories correctly",
    ),
    E2EScenario(
        id="S47", name="Alte Referenz mit Preissteigerung",
        category="combo",
        persona="FM, hat alten Referenzpreis und erwartet Erklärung für die Steigerung",
        gebaeude="Bürogebäude München, 3.500 m², Referenz 2020 für 3.000€",
        wissen="Kennt m², PLZ 80331, Referenzpreis 2020 = 3.000€, erwartet Erklärung warum teurer",
        absicht="DGUV V3, will Referenzpreisvergleich",
        max_turns=4,
        expected={"nutzung": "buerogebaeude", "flaeche_min": 3000, "flaeche_max": 4000, "kat": 2, "referenz": 3000},
        tricky_aspect="Old reference → significant price increase (~28.2% since 2020), must explain",
    ),
    E2EScenario(
        id="S48", name="Doppel-Zuschlag",
        category="combo",
        persona="Veranstaltungsmanager, braucht Eilprüfung und ist kein Vereinsmitglied",
        gebaeude="Kongresszentrum in Bonn, 3.500 m², Eilzuschlag weil Versicherung drängt",
        wissen="Kennt m², PLZ 53111, sagt klar: 'Wir sind kein TÜV-Vereinsmitglied und haben keinen Rahmenvertrag', Eile weil Versicherung Frist setzt",
        absicht="DGUV V3 mit Eilzuschlag, kein Vereinsmitglied",
        max_turns=4,
        expected={"nutzung": "versammlungsstaette", "flaeche_min": 3000, "flaeche_max": 4000, "kat": 3, "vereinsmitglied": False},
        tricky_aspect="Two surcharges stacked — Eil +25%, Nicht-Mitglied +20% → combined +50%",
    ),
    E2EScenario(
        id="S49", name="Hotel Komplett + Reifegrad 1",
        category="combo",
        persona="Eigentümer eines heruntergekommenen Hotels, will alles prüfen lassen",
        gebaeude="Hotel in Oberhof (Thüringen), 300 Zimmer, VdS, Restaurant, Tiefgarage, Reifegrad 1",
        wissen="Kennt Zimmer, PLZ 98559 (weit weg), Anlage in schlechtem Zustand",
        absicht="DGUV V3 + VdS kombiniert, schlechter Zustand, alle Details",
        max_turns=4,
        expected={"nutzung": "hotel", "flaeche_min": 8000, "flaeche_max": 10000, "kat": 2, "reifegrad": 1, "vds": True},
        tricky_aspect="Remote location + bad condition + large + VdS = expensive case with high Reisekosten",
    ),
    E2EScenario(
        id="S50", name="Golden Reference — Seniorentreff",
        category="combo",
        persona="Gemeinde-Sachbearbeiter, einfache Anfrage, Validierung gegen known price",
        gebaeude="Seniorentreff in Regensburg, 200 m², Kat 1, 1 UV, einfachste Ausstattung",
        wissen="Kennt m², PLZ 93047, einfache Anlage",
        absicht="DGUV V3",
        max_turns=4,
        expected={"nutzung": "seniorentreff", "flaeche_min": 180, "flaeche_max": 220, "kat": 1, "pinned_pruefkosten": 295},
        tricky_aspect="Golden reference — price must match pinned test value (295€ Prüfkosten ±5%)",
    ),
]

SCENARIO_MAP = {s.id: s for s in SCENARIOS}
